// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: entpb/catalog_ext.proto

package entpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogExtendedService_GetProducts_FullMethodName = "/entpb.CatalogExtendedService/GetProducts"
)

// CatalogExtendedServiceClient is the client API for CatalogExtendedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogExtendedServiceClient interface {
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
}

type catalogExtendedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogExtendedServiceClient(cc grpc.ClientConnInterface) CatalogExtendedServiceClient {
	return &catalogExtendedServiceClient{cc}
}

func (c *catalogExtendedServiceClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductsResponse)
	err := c.cc.Invoke(ctx, CatalogExtendedService_GetProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogExtendedServiceServer is the server API for CatalogExtendedService service.
// All implementations must embed UnimplementedCatalogExtendedServiceServer
// for forward compatibility.
type CatalogExtendedServiceServer interface {
	GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
	mustEmbedUnimplementedCatalogExtendedServiceServer()
}

// UnimplementedCatalogExtendedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogExtendedServiceServer struct{}

func (UnimplementedCatalogExtendedServiceServer) GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (UnimplementedCatalogExtendedServiceServer) mustEmbedUnimplementedCatalogExtendedServiceServer() {
}
func (UnimplementedCatalogExtendedServiceServer) testEmbeddedByValue() {}

// UnsafeCatalogExtendedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogExtendedServiceServer will
// result in compilation errors.
type UnsafeCatalogExtendedServiceServer interface {
	mustEmbedUnimplementedCatalogExtendedServiceServer()
}

func RegisterCatalogExtendedServiceServer(s grpc.ServiceRegistrar, srv CatalogExtendedServiceServer) {
	// If the following call pancis, it indicates UnimplementedCatalogExtendedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogExtendedService_ServiceDesc, srv)
}

func _CatalogExtendedService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogExtendedServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogExtendedService_GetProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogExtendedServiceServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogExtendedService_ServiceDesc is the grpc.ServiceDesc for CatalogExtendedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogExtendedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "entpb.CatalogExtendedService",
	HandlerType: (*CatalogExtendedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _CatalogExtendedService_GetProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entpb/catalog_ext.proto",
}
