// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: entpb/catalog_ext.proto

package entpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductsRequest_View int32

const (
	GetProductsRequest_VIEW_UNSPECIFIED GetProductsRequest_View = 0
	GetProductsRequest_BASIC            GetProductsRequest_View = 1
	GetProductsRequest_WITH_EDGE_IDS    GetProductsRequest_View = 2
)

// Enum value maps for GetProductsRequest_View.
var (
	GetProductsRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetProductsRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetProductsRequest_View) Enum() *GetProductsRequest_View {
	p := new(GetProductsRequest_View)
	*p = x
	return p
}

func (x GetProductsRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetProductsRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_catalog_ext_proto_enumTypes[0].Descriptor()
}

func (GetProductsRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_catalog_ext_proto_enumTypes[0]
}

func (x GetProductsRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetProductsRequest_View.Descriptor instead.
func (GetProductsRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_catalog_ext_proto_rawDescGZIP(), []int{0, 0}
}

type GetProductsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	PageSize      int64                   `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                  `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Query         *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	View          GetProductsRequest_View `protobuf:"varint,4,opt,name=view,proto3,enum=entpb.GetProductsRequest_View" json:"view,omitempty"`
	Ids           []string                `protobuf:"bytes,5,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_entpb_catalog_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_catalog_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_entpb_catalog_ext_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetProductsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *GetProductsRequest) GetQuery() *wrapperspb.StringValue {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *GetProductsRequest) GetView() GetProductsRequest_View {
	if x != nil {
		return x.View
	}
	return GetProductsRequest_VIEW_UNSPECIFIED
}

func (x *GetProductsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Catalog             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsResponse) Reset() {
	*x = GetProductsResponse{}
	mi := &file_entpb_catalog_ext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsResponse) ProtoMessage() {}

func (x *GetProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_catalog_ext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return file_entpb_catalog_ext_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductsResponse) GetProducts() []*Catalog {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *GetProductsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *GetProductsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_entpb_catalog_ext_proto protoreflect.FileDescriptor

const file_entpb_catalog_ext_proto_rawDesc = "" +
	"\n" +
	"\x17entpb/catalog_ext.proto\x12\x05entpb\x1a\x11entpb/entpb.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x86\x02\n" +
	"\x12GetProductsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x122\n" +
	"\x05query\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x05query\x122\n" +
	"\x04view\x18\x04 \x01(\x0e2\x1e.entpb.GetProductsRequest.ViewR\x04view\x12\x10\n" +
	"\x03ids\x18\x05 \x03(\tR\x03ids\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"\x8a\x01\n" +
	"\x13GetProductsResponse\x12*\n" +
	"\bproducts\x18\x01 \x03(\v2\x0e.entpb.CatalogR\bproducts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount2^\n" +
	"\x16CatalogExtendedService\x12D\n" +
	"\vGetProducts\x12\x19.entpb.GetProductsRequest\x1a\x1a.entpb.GetProductsResponseBCZAgithub.com/abisalde/gprc-microservice/catalog/pkg/ent/proto/entpbb\x06proto3"

var (
	file_entpb_catalog_ext_proto_rawDescOnce sync.Once
	file_entpb_catalog_ext_proto_rawDescData []byte
)

func file_entpb_catalog_ext_proto_rawDescGZIP() []byte {
	file_entpb_catalog_ext_proto_rawDescOnce.Do(func() {
		file_entpb_catalog_ext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entpb_catalog_ext_proto_rawDesc), len(file_entpb_catalog_ext_proto_rawDesc)))
	})
	return file_entpb_catalog_ext_proto_rawDescData
}

var file_entpb_catalog_ext_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_entpb_catalog_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_entpb_catalog_ext_proto_goTypes = []any{
	(GetProductsRequest_View)(0),   // 0: entpb.GetProductsRequest.View
	(*GetProductsRequest)(nil),     // 1: entpb.GetProductsRequest
	(*GetProductsResponse)(nil),    // 2: entpb.GetProductsResponse
	(*wrapperspb.StringValue)(nil), // 3: google.protobuf.StringValue
	(*Catalog)(nil),                // 4: entpb.Catalog
}
var file_entpb_catalog_ext_proto_depIdxs = []int32{
	3, // 0: entpb.GetProductsRequest.query:type_name -> google.protobuf.StringValue
	0, // 1: entpb.GetProductsRequest.view:type_name -> entpb.GetProductsRequest.View
	4, // 2: entpb.GetProductsResponse.products:type_name -> entpb.Catalog
	1, // 3: entpb.CatalogExtendedService.GetProducts:input_type -> entpb.GetProductsRequest
	2, // 4: entpb.CatalogExtendedService.GetProducts:output_type -> entpb.GetProductsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_entpb_catalog_ext_proto_init() }
func file_entpb_catalog_ext_proto_init() {
	if File_entpb_catalog_ext_proto != nil {
		return
	}
	file_entpb_entpb_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entpb_catalog_ext_proto_rawDesc), len(file_entpb_catalog_ext_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entpb_catalog_ext_proto_goTypes,
		DependencyIndexes: file_entpb_catalog_ext_proto_depIdxs,
		EnumInfos:         file_entpb_catalog_ext_proto_enumTypes,
		MessageInfos:      file_entpb_catalog_ext_proto_msgTypes,
	}.Build()
	File_entpb_catalog_ext_proto = out.File
	file_entpb_catalog_ext_proto_goTypes = nil
	file_entpb_catalog_ext_proto_depIdxs = nil
}
